### ISSUE TITLE
服务器部署完成后，启动失败，手动启动发现如下异常

### ISSUE THREAD

**Issue by huoxiaojun2009** [mafeicnnui/dbops#7]
看启动脚本，应该是这样启动服务的，手动执行：
python3 -u /data/myapp/easebase/web/controller/server.py 8201
Traceback (most recent call last):
  File "/data/myapp/easebase/web/controller/server.py", line 17, in <module>
    from web.utils.urls   import urls
ModuleNotFoundError: No module named 'web'

**Comment by huoxiaojun2009** [comment]
cat requirements.txt
humanize-3.14.0
这个有错误
应该 humanize==3.14.0

**Comment by mafeicnnui** [comment]
> cat requirements.txt humanize-3.14.0 这个有错误 应该 humanize==3.14.0

感谢，已经修好了

**Comment by mafeicnnui** [comment]
> 看启动脚本，应该是这样启动服务的，手动执行： python3 -u /data/myapp/easebase/web/controller/server.py 8201 Traceback (most recent call last): File "/data/myapp/easebase/web/controller/server.py", line 17, in from web.utils.urls import urls ModuleNotFoundError: No module named 'web'

![image](https://github.com/user-attachments/assets/c01a5306-9640-4a41-a2a6-8ecb809a10d1)

**Comment by huoxiaojun2009** [comment]
> > 看启动脚本，应该是这样启动服务的，手动执行： python3 -u /data/myapp/easebase/web/controller/server.py 8201 Traceback (most recent call last): File "/data/myapp/easebase/web/controller/server.py", line 17, in from web.utils.urls import urls ModuleNotFoundError: No module named 'web'
> 
> ![image](https://private-user-images.githubusercontent.com/13817818/387955337-c01a5306-9640-4a41-a2a6-8ecb809a10d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTQ4MTMsIm5iZiI6MTczMjExNDUxMywicGF0aCI6Ii8xMzgxNzgxOC8zODc5NTUzMzctYzAxYTUzMDYtOTY0MC00YTQxLWEyYTYtOGVjYjgwOWExMGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE0NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYmFlYmMwMjg1ZDlhMWUxMWQ1YTQyY2M0NTdhNzkxMTFhZDQzNjc1ZjIwNGUwY2Q3NGZkNWQxMjcwZmQ1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bJ-zW_qqKvLBiKrmHAtXKEXnapssvXmL0bSAawrSCBE)

手动设置环境变量，手动启动发现缺少包
[root@easedb dbops]# export PYTHONPATH=/data/myapp/dbops
[root@easedb dbops]# python3 -u /data/myapp/dbops/web/controller/server.py 8201
Traceback (most recent call last):
  File "/data/myapp/dbops/web/controller/server.py", line 18, in <module>
    from web.utils.urls   import urls
  File "/data/myapp/dbops/web/utils/urls.py", line 32, in <module>
    from web.urls.bbgl     import bbgl
  File "/data/myapp/dbops/web/urls/bbgl.py", line 8, in <module>
    from web.services.bbgl import bbgl_add, bbgl_add_save, bbgl_add_header_save, bbgl_header_query, bbgl_query_dm, \
  File "/data/myapp/dbops/web/services/bbgl.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
安装完这个包后，启动成功

**Comment by huoxiaojun2009** [comment]
![image](https://github.com/user-attachments/assets/3345c7a6-3bf0-470b-86aa-1052769751cc)
服务启动后，显示服务不可用

**Comment by mafeicnnui** [comment]
正常登陆时，验证码是可以正常展示的
![image](https://github.com/user-attachments/assets/a2ddae98-4546-45ed-a11a-36612f3b091c)

**Comment by huoxiaojun2009** [comment]
![图片](https://github.com/user-attachments/assets/c8b75c4f-4f29-48ed-94c2-45a9f14b838d)

验证码可以正常显示

**Comment by huoxiaojun2009** [comment]
我重新启动了个端口
[root@easedb dbops]# python3 -u /data/myapp/dbops/web/controller/server.py 8211
Dbops Server running 8211 port ..

访问:http://192.168.90.61:8211/login 正常
[W 241121 12:59:00 web:1787] 400 GET / (192.168.90.1): Missing argument token
[I 241121 12:59:00 web:2243] 302 GET / (192.168.90.1) 0.72ms
[I 241121 12:59:00 web:2243] 304 GET /login (192.168.90.1) 6.96ms
![图片](https://github.com/user-attachments/assets/c4fe515c-65e4-4187-bf70-98d83b8db5a9)

登录时候出现异常
[I 241121 12:59:01 web:2243] 200 POST /get_verify (192.168.90.1) 34.81ms
[I 241121 12:59:01 web:2243] 200 GET /static/assets/images/logon/verifyFxUEq.png (192.168.90.1) 2.85ms


[I 241121 12:56:25 web:2243] 200 GET /static/plugins/morris/morris.min.js (192.168.90.1) 0.87ms
[I 241121 12:56:25 web:2243] 200 GET /static/plugins/toastr/toastr.min.js (192.168.90.1) 0.54ms
[I 241121 12:56:25 web:2243] 200 GET /static/assets/fonts/ionicons.ttf?v=1.5.0 (192.168.90.1) 1.56ms
[I 241121 12:56:25 web:2243] 200 GET /static/plugins/echarts/echarts.min.js (192.168.90.1) 15.66ms
[I 241121 12:56:25 web:2243] 200 GET /static/assets/fonts/materialdesignicons-webfont.woff2?v=1.6.50 (192.168.90.1) 1.78ms
[I 241121 12:56:25 web:2243] 200 GET /static/assets/fonts/fontawesome-webfont.woff2?v=4.6.3 (192.168.90.1) 1.55ms
3
[I 241121 12:56:25 web:2243] 200 POST /get_verify (192.168.90.1) 35.72ms
[W 241121 12:56:25 web:2243] 404 GET /favicon.ico (192.168.90.1) 3.64ms
[I 241121 12:56:25 web:2243] 200 GET /static/assets/images/logon/verifyQirB5.png (192.168.90.1) 1.65ms
[E 241121 12:56:36 web:1793] Uncaught exception POST /logon_check (192.168.90.1)
    HTTPServerRequest(protocol='http', host='192.168.90.61:8211', method='POST', uri='/logon_check', version='HTTP/1.1', remote_ip='192.168.90.1')
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/data/myapp/dbops/web/services/logon.py", line 33, in post
        token = await self.create_token({"username": username, "userid": d_user['userid'],"name":d_user['name'],"remote_ip":remote_ip})
      File "/data/myapp/dbops/web/utils/base_handler.py", line 43, in create_token
        result = jwt.encode(payload=payload, key=JWT_SALT, algorithm="HS256", headers=headers)
    AttributeError: module 'jwt' has no attribute 'encode'
[E 241121 12:56:36 web:2243] 500 POST /logon_check (192.168.90.1) 44.88ms
[I 241121 12:56:36 web:2243] 200 GET /static/assets/images/bg-pattern.png (192.168.90.1) 0.84ms

**Comment by huoxiaojun2009** [comment]
按如下操作后
[root@easedb nginx]# pip3 uninstall jwt
Uninstalling jwt-1.3.1:
  /usr/local/lib/python3.6/site-packages/jwt-1.3.1.dist-info/INSTALLER
  /usr/local/lib/python3.6/site-packages/jwt-1.3.1.dist-info/LICENSE
  /usr/local/lib/python3.6/site-packages/jwt-1.3.1.dist-info/METADATA
  /usr/local/lib/python3.6/site-packages/jwt-1.3.1.dist-info/RECORD
  /usr/local/lib/python3.6/site-packages/jwt-1.3.1.dist-info/WHEEL
  /usr/local/lib/python3.6/site-packages/jwt-1.3.1.dist-info/top_level.txt
  /usr/local/lib/python3.6/site-packages/jwt/__init__.py
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/exceptions.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/jwa.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/jwk.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/jwkset.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/jws.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/jwt.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/utils.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/exceptions.py
  /usr/local/lib/python3.6/site-packages/jwt/jwa.py
  /usr/local/lib/python3.6/site-packages/jwt/jwk.py
  /usr/local/lib/python3.6/site-packages/jwt/jwkset.py
  /usr/local/lib/python3.6/site-packages/jwt/jws.py
  /usr/local/lib/python3.6/site-packages/jwt/jwt.py
  /usr/local/lib/python3.6/site-packages/jwt/py.typed
  /usr/local/lib/python3.6/site-packages/jwt/utils.py
Proceed (y/n)? y
  Successfully uninstalled jwt-1.3.1
[root@easedb nginx]# pip3 uninstall PyJWT
Uninstalling PyJWT-2.1.0:
  /usr/local/lib/python3.6/site-packages/PyJWT-2.1.0.dist-info/AUTHORS.rst
  /usr/local/lib/python3.6/site-packages/PyJWT-2.1.0.dist-info/INSTALLER
  /usr/local/lib/python3.6/site-packages/PyJWT-2.1.0.dist-info/LICENSE
  /usr/local/lib/python3.6/site-packages/PyJWT-2.1.0.dist-info/METADATA
  /usr/local/lib/python3.6/site-packages/PyJWT-2.1.0.dist-info/RECORD
  /usr/local/lib/python3.6/site-packages/PyJWT-2.1.0.dist-info/WHEEL
  /usr/local/lib/python3.6/site-packages/PyJWT-2.1.0.dist-info/top_level.txt
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/algorithms.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/api_jwk.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/api_jws.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/api_jwt.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/help.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/__pycache__/jwks_client.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/jwt/algorithms.py
  /usr/local/lib/python3.6/site-packages/jwt/api_jwk.py
  /usr/local/lib/python3.6/site-packages/jwt/api_jws.py
  /usr/local/lib/python3.6/site-packages/jwt/api_jwt.py
  /usr/local/lib/python3.6/site-packages/jwt/help.py
  /usr/local/lib/python3.6/site-packages/jwt/jwks_client.py
Proceed (y/n)? y
  Successfully uninstalled PyJWT-2.1.0
[root@easedb nginx]# pip3 install PyJWT
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting PyJWT
  Downloading https://files.pythonhosted.org/packages/1c/fb/b82e9601b00d88cf8bbee1f39b855ae773f9d5bcbcedb3801b2f72460696/PyJWT-2.4.0-py3-none-any.whl
Installing collected packages: PyJWT
Successfully installed PyJWT-2.4.0
可以登录进系统
近来出现如下异常
![图片](https://github.com/user-attachments/assets/4781c0e8-e55e-40c2-8335-946dff84b4d6)

后台如下报错
[I 241121 13:21:28 web:2243] 200 GET /static/assets/images/users/boy.png (192.168.90.1) 3.40ms
verified_payload= {'username': 'admin', 'userid': '1', 'name': '管理员', 'remote_ip': '', 'exp': 1732168288, 'iat': 1732166488, 'iss': 'zhitbar.cn', 'session_id': 3241}
verified_payload= {'username': 'admin', 'userid': '1', 'name': '管理员', 'remote_ip': '', 'exp': 1732168288, 'iat': 1732166488, 'iss': 'zhitbar.cn', 'session_id': 3241}
[E 241121 13:21:28 web:1793] Uncaught exception POST /get/db/order/num (192.168.90.1)
    HTTPServerRequest(protocol='http', host='192.168.90.61:8211', method='POST', uri='/get/db/order/num', version='HTTP/1.1', remote_ip='192.168.90.1')
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/data/myapp/dbops/web/services/sync.py", line 582, in post
        v_list      = await query_db_order_num()
      File "/data/myapp/dbops/web/model/t_sync.py", line 1403, in query_db_order_num
        for r in await async_processer.query_list(sql):
      File "/data/myapp/dbops/web/utils/mysql_async.py", line 48, in query_list
        await cur.execute(p_sql)
      File "/usr/local/lib/python3.6/site-packages/aiomysql/cursors.py", line 239, in execute
        await self._query(query)
      File "/usr/local/lib/python3.6/site-packages/aiomysql/cursors.py", line 457, in _query
        await conn.query(q)
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 428, in query
        await self._read_query_result(unbuffered=unbuffered)
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 622, in _read_query_result
        await result.read()
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 1105, in read
        first_packet = await self.connection._read_packet()
      File "/usr/local/lib/python3.6/site-packages/aiomysql/connection.py", line 593, in _read_packet
        packet.check_error()
      File "/usr/local/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
        err.raise_mysql_exception(self._data)
      File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
        raise errorclass(errno, errval)
    pymysql.err.ProgrammingError: (1146, "Table 'puppet.help_topic' doesn't exist")
[E 241121 13:21:28 web:2243] 500 POST /get/db/order/num (192.168.90.1) 12.83ms

**Comment by mafeicnnui** [comment]
1.删除了jwt包
2.提交了缺失的表：sql/table/cre_tab.sql

**Comment by huoxiaojun2009** [comment]
谢谢，问题得到解决
